### PR TITLE
Update to v1.5.1

### PR DESCRIPTION
**Pull request by ajdawson**
Updating the package version to v1.5.1.

### CODE REVIEW

**Comment by ajdawson** [comment]
The osx build is failing due to what I assume is a systematic error, should I rerender this feedstock? ping @ocefpaf

**Comment by ocefpaf** [comment]
> The osx build is failing due to what I assume is a systematic error, should I rerender this feedstock?

Re-rendering will fix that but will also add Python 3.6 to the matrix. Not sure if we have all the dependencies ready for `windspharm`, but I am working on it.

**Comment by ajdawson** [comment]
OK, yeah you called it perfectly, the rerender fails because pyspharm has no 3.6 build.

**Comment by ocefpaf** [comment]
I am working on pyspharm now. Hold on...

**Comment by ajdawson** [comment]
This look right @ocefpaf?

**Comment by ocefpaf** [comment]
> This look right @ocefpaf?

Perfect!

@ajdawson in conda-forge updates like this are OK to self-merge. We only expect review when there is a non-automatic (re-rendering) functional change to the feedstock. However, feel free to ping me anytime.

**Comment by ajdawson** [comment]
OK cheers, thanks for the help.

**Pull request merged**
